defmodule Helpdesk.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      modify :additional_data, :map, default: %{}
    end
  end

  def down do
    alter table(:tickets) do
      modify :additional_data, :map, default: nil
    end
  end
end
